name = "fisiolipo-crm-worker"
main = "src/index.ts"
compatibility_date = "2026-07-03"

[[d1_databases]]
binding = "DB"
database_name = "fisiolipo-crm-chat"
database_id = "cdd1129f-54a7-43a0-8247-972781bb9e02"
